kind: pipeline
name: default

steps:
  - name: validate
    image: golang
    commands:
      - go build
      - go test
  - name: docker
    image: plugins/docker
    settings:
      username: chandlerswift
      password:
        from_secret: docker_hub_password
      repo: chandlerswift/go-fibserv
      auto_tag: true
